#!/usr/bin/env bash
# This script is displaying Numbers from 1 - 20
# Displays "bad luck from China", "bad luck from Japan" and "bad luck from Italy"

i=0

while ((i <= 20))
do
  echo "$i"
  case $i in 
    4) echo "bad luck from China";;
    9) echo "bad luck from Japan";;
    17) echo "bad luck from Italy";;
  esac
    ((i++))
done
