#!/usr/bin/env bash
# This script is displaying time for 12hrs and 59 minutes

hour=0

while (( hour <= 12 ))
do
  echo "Hour: $hour"
  minute=1
  while (( minute <= 59 ))
  do
    echo "$minute"
    (( minute++ ))
  done
  (( hour++ ))
done
